<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <OutputPath>bin\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <PublishDir>bin\publish\</PublishDir>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishSelfContained>true</PublishSelfContained>
        <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <AllowedReferenceRelatedFileExtensions>.none</AllowedReferenceRelatedFileExtensions>
        <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FFXIVClientStructs.StandaloneHost\FFXIVClientStructs.StandaloneHost.csproj" />
    </ItemGroup>

</Project>
